/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

import java.io.Serializable;

/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class AlarmItem implements Serializable {

	private static final long serialVersionUID = -987395170636781619L;
	@org.codehaus.jackson.annotate.JsonProperty("id")
	private java.lang.String id;

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getId() {
		return id;
	}

	@org.codehaus.jackson.annotate.JsonProperty("substation_name")
	private java.lang.String substation_name;

	public void setSubstation_name(java.lang.String substation_name) {
		this.substation_name = substation_name;
	}

	public java.lang.String getSubstation_name() {
		return substation_name;
	}

	@org.codehaus.jackson.annotate.JsonProperty("room_location")
	private java.lang.String room_location;

	public void setRoom_location(java.lang.String room_location) {
		this.room_location = room_location;
	}

	public java.lang.String getRoom_location() {
		return room_location;
	}

	@org.codehaus.jackson.annotate.JsonProperty("status")
	private java.lang.String status;

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getStatus() {
		return status;
	}

	@org.codehaus.jackson.annotate.JsonProperty("dev_model")
	private java.lang.String dev_model;

	public void setDev_model(java.lang.String dev_model) {
		this.dev_model = dev_model;
	}

	public java.lang.String getDev_model() {
		return dev_model;
	}

	@org.codehaus.jackson.annotate.JsonProperty("room_id")
	private java.lang.String room_id;
	public java.lang.String getRoom_id() {
		return room_id;
	}

	public void setRoom_id(java.lang.String room_id) {
		this.room_id = room_id;
	}

	@org.codehaus.jackson.annotate.JsonProperty("room_name")
	private java.lang.String room_name;

	public void setRoom_name(java.lang.String room_name) {
		this.room_name = room_name;
	}

	public java.lang.String getRoom_name() {
		return room_name;
	}

	@org.codehaus.jackson.annotate.JsonProperty("data_id")
	private java.lang.String data_id;

	public void setData_id(java.lang.String data_id) {
		this.data_id = data_id;
	}

	public java.lang.String getData_id() {
		return data_id;
	}

	@org.codehaus.jackson.annotate.JsonProperty("city_code")
	private java.lang.String city_code;

	public void setCity_code(java.lang.String city_code) {
		this.city_code = city_code;
	}

	public java.lang.String getCity_code() {
		return city_code;
	}

	@org.codehaus.jackson.annotate.JsonProperty("room_code")
	private java.lang.String room_code;

	public void setRoom_code(java.lang.String room_code) {
		this.room_code = room_code;
	}

	public java.lang.String getRoom_code() {
		return room_code;
	}

	@org.codehaus.jackson.annotate.JsonProperty("county")
	private java.lang.String county;

	public void setCounty(java.lang.String county) {
		this.county = county;
	}

	public java.lang.String getCounty() {
		return county;
	}

	@org.codehaus.jackson.annotate.JsonProperty("confirm_datetime")
	private java.lang.String confirm_datetime;

	public void setConfirm_datetime(java.lang.String confirm_datetime) {
		this.confirm_datetime = confirm_datetime;
	}

	public java.lang.String getConfirm_datetime() {
		return confirm_datetime;
	}

	@org.codehaus.jackson.annotate.JsonProperty("added_datetime")
	private java.lang.String added_datetime;

	public void setAdded_datetime(java.lang.String added_datetime) {
		this.added_datetime = added_datetime;
	}

	public java.lang.String getAdded_datetime() {
		return added_datetime;
	}

	@org.codehaus.jackson.annotate.JsonProperty("restore_datetime")
	private java.lang.String restore_datetime;

	public void setRestore_datetime(java.lang.String restore_datetime) {
		this.restore_datetime = restore_datetime;
	}

	public java.lang.String getRestore_datetime() {
		return restore_datetime;
	}

	@org.codehaus.jackson.annotate.JsonProperty("dev_name")
	private java.lang.String dev_name;

	public void setDev_name(java.lang.String dev_name) {
		this.dev_name = dev_name;
	}

	public java.lang.String getDev_name() {
		return dev_name;
	}

	@org.codehaus.jackson.annotate.JsonProperty("subject")
	private java.lang.String subject;

	public void setSubject(java.lang.String subject) {
		this.subject = subject;
	}

	public java.lang.String getSubject() {
		return subject;
	}

	@org.codehaus.jackson.annotate.JsonProperty("level")
	private java.lang.Integer level;

	public void setLevel(java.lang.Integer level) {
		this.level = level;
	}

	public java.lang.Integer getLevel() {
		return level;
	}

	@org.codehaus.jackson.annotate.JsonProperty("city")
	private java.lang.String city;

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getCity() {
		return city;
	}

	@org.codehaus.jackson.annotate.JsonProperty("county_code")
	private java.lang.String county_code;

	public void setCounty_code(java.lang.String county_code) {
		this.county_code = county_code;
	}

	public java.lang.String getCounty_code() {
		return county_code;
	}

	@org.codehaus.jackson.annotate.JsonProperty("signal_name")
	private java.lang.String signalName;

	@org.codehaus.jackson.annotate.JsonProperty("signal_id")
	private java.lang.String signalId;

	@Override
	public boolean equals(Object o) {
		if (!(o instanceof AlarmItem))
			return false;
		AlarmItem a = (AlarmItem) o;
		return this.id == a.id;
	}

	public java.lang.String getSignalName() {
		return signalName;
	}

	public void setSignalName(java.lang.String signalName) {
		this.signalName = signalName;
	}

	public java.lang.String getSignalId() {
		return signalId;
	}

	public void setSignalId(java.lang.String signalId) {
		this.signalId = signalId;
	}

	@Override
	public String toString() {
		return "AlarmItem [id=" + id + ", substation_name=" + substation_name + ", room_location=" + room_location
				+ ", status=" + status + ", dev_model=" + dev_model + ", room_id=" + room_id + ", room_name="
				+ room_name + ", data_id=" + data_id + ", city_code=" + city_code + ", room_code=" + room_code
				+ ", county=" + county + ", confirm_datetime=" + confirm_datetime + ", added_datetime=" + added_datetime
				+ ", restore_datetime=" + restore_datetime + ", dev_name=" + dev_name + ", subject=" + subject
				+ ", level=" + level + ", city=" + city + ", county_code=" + county_code + ", signalName=" + signalName
				+ ", signalId=" + signalId + "]";
	}

}