/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class AlarmChartsItem {
	@org.codehaus.jackson.annotate.JsonProperty("name")
	private java.lang.String name;

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

	@org.codehaus.jackson.annotate.JsonProperty("alarm_level_3")
	private java.lang.Integer alarm_level_3;

	public void setAlarm_level_3(java.lang.Integer alarm_level_3) {
		this.alarm_level_3 = alarm_level_3;
	}

	public java.lang.Integer getAlarm_level_3() {
		return alarm_level_3;
	}

	@org.codehaus.jackson.annotate.JsonProperty("alarm_level_4")
	private java.lang.Integer alarm_level_4;

	public void setAlarm_level_4(java.lang.Integer alarm_level_4) {
		this.alarm_level_4 = alarm_level_4;
	}

	public java.lang.Integer getAlarm_level_4() {
		return alarm_level_4;
	}

	@org.codehaus.jackson.annotate.JsonProperty("alarm_level_1")
	private java.lang.Integer alarm_level_1;

	public void setAlarm_level_1(java.lang.Integer alarm_level_1) {
		this.alarm_level_1 = alarm_level_1;
	}

	public java.lang.Integer getAlarm_level_1() {
		return alarm_level_1;
	}

	@org.codehaus.jackson.annotate.JsonProperty("alarm_level_2")
	private java.lang.Integer alarm_level_2;

	public void setAlarm_level_2(java.lang.Integer alarm_level_2) {
		this.alarm_level_2 = alarm_level_2;
	}

	public java.lang.Integer getAlarm_level_2() {
		return alarm_level_2;
	}

}