/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

public class AlarmResp {
	@org.codehaus.jackson.annotate.JsonProperty("alarmList")
	private AlarmItem[] alarmlist;

	public void setAlarmlist(AlarmItem[] alarmlist) {
		this.alarmlist = alarmlist;
	}

	public AlarmItem[] getAlarmlist() {
		return alarmlist;
	}

	@org.codehaus.jackson.annotate.JsonProperty("alarmCount")
	private java.lang.Integer alarmcount;

	public void setAlarmcount(java.lang.Integer alarmcount) {
		this.alarmcount = alarmcount;
	}

	public java.lang.Integer getAlarmcount() {
		return alarmcount;
	}

}