/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class AlarmChartsResp {
	@org.codehaus.jackson.annotate.JsonProperty("title")
	private java.lang.String title;

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getTitle() {
		return title;
	}

	@org.codehaus.jackson.annotate.JsonProperty("alarmChartsDataList")
	private AlarmChartsItem[] alarmChartsDataList;

	public void setAlarmchartsdatalist(AlarmChartsItem[] alarmChartsDataList) {
		this.alarmChartsDataList = alarmChartsDataList;
	}

	public AlarmChartsItem[] getAlarmChartsDataList() {
		return alarmChartsDataList;
	}

}