/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class ApiResponse {
	@org.codehaus.jackson.annotate.JsonProperty("ret")
	private java.lang.Integer ret;

	public void setRet(java.lang.Integer ret) {
		this.ret = ret;
	}

	public java.lang.Integer getRet() {
		return ret;
	}

	@org.codehaus.jackson.annotate.JsonProperty("data")
	private java.lang.String data;

	public void setData(java.lang.String data) {
		this.data = data;
	}

	public java.lang.String getData() {
		return data;
	}

	@org.codehaus.jackson.annotate.JsonProperty("stationimg")
	private java.lang.String stationimg;

	public java.lang.String getStationimg() {
		return stationimg;
	}

	public void setStationimg(java.lang.String stationimg) {
		this.stationimg = stationimg;
	}

	@org.codehaus.jackson.annotate.JsonProperty("response")
	private java.lang.String response;

	public java.lang.String getResponse() {
		return response;
	}

	public void setResponse(java.lang.String response) {
		this.response = response;
	}

	@org.codehaus.jackson.annotate.JsonProperty("mobile")
	private java.lang.String mobile;

	public java.lang.String getMobile() {
		return mobile;
	}

	public void setMobile(java.lang.String mobile) {
		this.mobile = mobile;
	}

	@Override
	public String toString() {
		return "ApiResponse [ret=" + ret + ", data=" + data + ", stationimg=" + stationimg + ", response=" + response
				+ ", mobile=" + mobile + "]";
	}

}