/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class ApiResponseStationList  {
	
	@org.codehaus.jackson.annotate.JsonProperty("stationList")
	private StationList[] stationList;

	public StationList[] getStationLists() {
		return stationList;
	}

	public void setStationLists(StationList[] stationImg) {
		this.stationList = stationImg;
	}

	@org.codehaus.jackson.annotate.JsonProperty("filename")
	private String[] filename;

	public StationList[] getStationList() {
		return stationList;
	}

	public void setStationList(StationList[] stationList) {
		this.stationList = stationList;
	}

	public String[] getFilename() {
		return filename;
	}

	public void setFilename(String[] filename) {
		this.filename = filename;
	}

	@org.codehaus.jackson.annotate.JsonProperty("data")
	private StationList[] data;

}