/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;
/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class ApiResponse {
	@org.codehaus.jackson.annotate.JsonProperty("ret")
	private java.lang.Integer ret;

	public void setRet(java.lang.Integer ret) {
		this.ret = ret;
	}

	public java.lang.Integer getRet() {
		return ret;
	}

	@org.codehaus.jackson.annotate.JsonProperty("data")
	private java.lang.String data;

	public void setData(java.lang.String data) {
		this.data = data;
	}

	public java.lang.String getData() {
		return data;
	}

}