/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;
/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class CountyItem {
	@org.codehaus.jackson.annotate.JsonProperty("name")
	private java.lang.String name;

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

	@org.codehaus.jackson.annotate.JsonProperty("substationList")
	private SubstationItem[] substationlist;

	public void setSubstationlist(SubstationItem[] substationlist) {
		this.substationlist = substationlist;
	}

	public SubstationItem[] getSubstationlist() {
		return substationlist;
	}

	@org.codehaus.jackson.annotate.JsonProperty("code")
	private java.lang.String code;

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public java.lang.String getCode() {
		return code;
	}

}