/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;
/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class DevModelItem {
	@org.codehaus.jackson.annotate.JsonProperty("key")
	private java.lang.String key;

	public void setKey(java.lang.String key) {
		this.key = key;
	}

	public java.lang.String getKey() {
		return key;
	}

	@org.codehaus.jackson.annotate.JsonProperty("val")
	private java.lang.String val;

	public void setVal(java.lang.String val) {
		this.val = val;
	}

	public java.lang.String getVal() {
		return val;
	}

}