/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class LoginResponse {
	public LoginResponse(Integer ret, String response, String error) {
		super();
		this.error = error;
		this.ret = ret;
		this.response = response;
	}

	public LoginResponse() {
		super();
	}

	@org.codehaus.jackson.annotate.JsonProperty("error")
	private java.lang.String error;

	public void setError(java.lang.String error) {
		this.error = error;
	}

	public java.lang.String getError() {
		return error;
	}

	@org.codehaus.jackson.annotate.JsonProperty("ret")
	private java.lang.Integer ret;

	public void setRet(java.lang.Integer ret) {
		this.ret = ret;
	}

	public java.lang.Integer getRet() {
		return ret;
	}

	@org.codehaus.jackson.annotate.JsonProperty("response")
	private java.lang.String response;

	public void setResponse(java.lang.String response) {
		this.response = response;
	}

	public java.lang.String getResponse() {
		return response;
	}

}