/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;
/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class OauthRespose {
	@org.codehaus.jackson.annotate.JsonProperty("refresh_token")
	private java.lang.String refresh_token;

	public void setRefresh_token(java.lang.String refresh_token) {
		this.refresh_token = refresh_token;
	}

	public java.lang.String getRefresh_token() {
		return refresh_token;
	}

	@org.codehaus.jackson.annotate.JsonProperty("token_type")
	private java.lang.String token_type;

	public void setToken_type(java.lang.String token_type) {
		this.token_type = token_type;
	}

	public java.lang.String getToken_type() {
		return token_type;
	}

	@org.codehaus.jackson.annotate.JsonProperty("expires_in")
	private java.lang.Integer expires_in;

	public void setExpires_in(java.lang.Integer expires_in) {
		this.expires_in = expires_in;
	}

	public java.lang.Integer getExpires_in() {
		return expires_in;
	}

	@org.codehaus.jackson.annotate.JsonProperty("access_token")
	private java.lang.String access_token;

	public void setAccess_token(java.lang.String access_token) {
		this.access_token = access_token;
	}

	public java.lang.String getAccess_token() {
		return access_token;
	}

	@org.codehaus.jackson.annotate.JsonProperty("expires")
	private java.lang.Integer expires;

	public void setExpires(java.lang.Integer expires) {
		this.expires = expires;
	}

	public java.lang.Integer getExpires() {
		return expires;
	}

}