/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

import java.util.Arrays;

import android.os.Parcel;
import android.os.Parcelable;

/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class SubstationItem implements Parcelable {
	@org.codehaus.jackson.annotate.JsonProperty("roomList")
	private RoomItem[] roomlist;

	public void setRoomlist(RoomItem[] roomlist) {
		this.roomlist = roomlist;
	}

	public RoomItem[] getRoomlist() {
		return roomlist;
	}

	@org.codehaus.jackson.annotate.JsonProperty("name")
	private java.lang.String name;

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

	@org.codehaus.jackson.annotate.JsonProperty("code")
	private java.lang.String code;

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public java.lang.String getCode() {
		return code;
	}

	@Override
	public int describeContents() {
		return 0;
	}

	@Override
	public void writeToParcel(Parcel out, int flags) {
		out.writeParcelableArray(roomlist, flags);
		out.writeString(code);
		out.writeString(name);
	}

	public static final Parcelable.Creator<SubstationItem> CREATOR = new Creator<SubstationItem>() {
		@Override
		public SubstationItem[] newArray(int size) {
			return new SubstationItem[size];
		}

		@Override
		public SubstationItem createFromParcel(Parcel in) {
			return new SubstationItem(in);
		}
	};

	public SubstationItem(Parcel in) {
		Parcelable[] parcelables = in.readParcelableArray(RoomItem.class.getClassLoader());
		if (parcelables != null) {
			roomlist = Arrays.copyOf(parcelables, parcelables.length, RoomItem[].class);
		}
		code = in.readString();
		name = in.readString();
	}

	public SubstationItem() {
		roomlist = new RoomItem[0];
		code = "";
		name = "";
	}

}