/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.chinatelecom.xjdh.bean;

import java.io.Serializable;
/**
 * @author peter
 * 
 */
@org.codehaus.jackson.annotate.JsonIgnoreProperties(ignoreUnknown = true)
public class UserInfo implements Serializable {

	private static final long serialVersionUID = 7220925282557754987L;
	@org.codehaus.jackson.annotate.JsonProperty("id")
	private java.lang.Integer id;

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getId() {
		return id;
	}

	@org.codehaus.jackson.annotate.JsonProperty("mobile")
	private java.lang.String mobile;

	public void setMobile(java.lang.String mobile) {
		this.mobile = mobile;
	}

	public java.lang.String getMobile() {
		return mobile;
	}

	@org.codehaus.jackson.annotate.JsonProperty("username")
	private java.lang.String username;

	public void setUsername(java.lang.String username) {
		this.username = username;
	}

	public java.lang.String getUsername() {
		return username;
	}

	@org.codehaus.jackson.annotate.JsonProperty("info")
	private java.lang.String info;

	public void setInfo(java.lang.String info) {
		this.info = info;
	}

	public java.lang.String getInfo() {
		return info;
	}

	@org.codehaus.jackson.annotate.JsonProperty("email")
	private java.lang.String email;

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getEmail() {
		return email;
	}

	@org.codehaus.jackson.annotate.JsonProperty("substation_id")
	private java.lang.Integer substation_id;

	public void setSubstation_id(java.lang.Integer substation_id) {
		this.substation_id = substation_id;
	}

	public java.lang.Integer getSubstation_id() {
		return substation_id;
	}

	@org.codehaus.jackson.annotate.JsonProperty("added_datetime")
	private java.lang.String added_datetime;

	public void setAdded_datetime(java.lang.String added_datetime) {
		this.added_datetime = added_datetime;
	}

	public java.lang.String getAdded_datetime() {
		return added_datetime;
	}

	@org.codehaus.jackson.annotate.JsonProperty("full_name")
	private java.lang.String full_name;

	public void setFull_name(java.lang.String full_name) {
		this.full_name = full_name;
	}

	public java.lang.String getFull_name() {
		return full_name;
	}

	@org.codehaus.jackson.annotate.JsonProperty("user_role")
	private java.lang.String user_role;

	public void setUser_role(java.lang.String user_role) {
		this.user_role = user_role;
	}

	public java.lang.String getUser_role() {
		return user_role;
	}

	@org.codehaus.jackson.annotate.JsonProperty("gender")
	private java.lang.String gender;

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public java.lang.String getGender() {
		return gender;
	}

	@org.codehaus.jackson.annotate.JsonProperty("user_image")
	private java.lang.String user_image;

	public void setUser_image(java.lang.String user_image) {
		this.user_image = user_image;
	}

	public java.lang.String getUser_image() {
		return user_image;
	}

	@Override
	public String toString() {
		return "UserInfo [id=" + id + ", mobile=" + mobile + ", username=" + username + ", info=" + info + ", email="
				+ email + ", substation_id=" + substation_id + ", added_datetime=" + added_datetime + ", full_name="
				+ full_name + ", user_role=" + user_role + ", gender=" + gender + ", user_image=" + user_image + "]";
	}
	
	
	
}